Added Homepage
zoyatanweer/falcon-store pull request #5
Opened 2022-02-17 17:14 UTC by zoyatanweer

![image](https://user-images.githubusercontent.com/87615284/154534325-3298d287-720f-4dbe-95c7-d0fefb0d1aa1.png)
![image](https://user-images.githubusercontent.com/87615284/154534411-fbaa12ea-b793-43e7-aac0-540bda929973.png)
This is the homepage.

![image](https://user-images.githubusercontent.com/87615284/154534598-5bb48e7b-50cf-4bcd-8c48-e811bca25ee7.png)
added profile avatar to products, wishlist and cart page.

2022-02-17 17:54 UTC, humzahasan commented on components/cart/cart.html
>                          <svg class="right-nav-img" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M16
Not related to this PR, but any reason why you are using svg tag directly here instead of have it from <img /> tag ?

2022-02-17 17:56 UTC, tonymike99 approved these changes
The code looks great! Styles are very neat.
Just one thing - the user avatar menu width is small and "My profile" comes on 2 lines.. You can correct that.

2022-02-17 18:01 UTC, humzahasan approved these changes
- Code Looks good. 
- Very appealing UI 

Suggestion : Consider using svg with img so that your html does not bloats. Also there is a small difference in performance when you use inline svg over img tag. 

Good to Merge!

2022-02-17 18:20 UTC, zoyatanweer commented on components/cart/cart.html
>                          <svg class="right-nav-img" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M16
Earlier I used to attach in <img>. Now I might have faced some issue so that's why I started linking directly the svg file.

2022-02-17 18:21 UTC, zoyatanweer commented
> The code looks great! Styles are very neat. Just one thing - the user avatar menu width is small and "My profile" comes on 2 lines.. You can correct that.

Hey, in mine "My Profile" comes on same line. Can you suggest me so that I can get this in same line in all the devices?

2022-02-17 18:22 UTC, zoyatanweer commented
> * Code Looks good.
> * Very appealing UI
> 
> Suggestion : Consider using svg with img so that your html does not bloats. Also there is a small difference in performance when you use inline svg over img tag.
> 
> Good to Merge!

Thanks Humza for your review. Will again try to link it to img.

2022-02-18 02:19 UTC, tonymike99 commented
> > The code looks great! Styles are very neat. Just one thing - the user avatar menu width is small and "My profile" comes on 2 lines.. You can correct that.
> 
> Hey, in mine "My Profile" comes on same line. Can you suggest me so that I can get this in same line in all the devices?

Hi Zoya, 
If you want the profile menu in one line, increase the width of ".profile-menu"
If you want the profile menu to be stacked, remove "display: inline" for ".right-nav li" (This will look better in my opinion)

2022-02-18 05:25 UTC, zoef-yt requested changes

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    border: 2px solid black;
use var for colour

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    /* margin-right: 0; */
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    /* bottom: -15rem; */
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    /* max-width: 50rem; */
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    /* margin-bottom: 0; */
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    /* position: relative; */
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on components/homepage/homepage.css
> +    top:270px;
use rem.

2022-02-18 05:25 UTC, zoef-yt commented on index.html
> +            <!-- <svg class="featured-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--ic" width="32" height="3
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on index.html
> +                  <!-- <button class="btn-icon btn-icon-cart">3</button> -->
remove commented code.

2022-02-18 05:25 UTC, zoef-yt commented on index.html
> +                  <!-- <button class="btn-icon btn-icon-wishlist">4</button> -->
remove commented code.

2022-02-18 09:44 UTC, saurabhchirde approved these changes
Looks good to merge, just some suggestions as per UX point of view.

![Screenshot 2022-02-18 at 3 00 51 PM](https://user-images.githubusercontent.com/92800463/154656690-577bcc7a-e751-4189-bf0e-656c1aa3ccbb.png)
It would be more accessible if you could give some breathing space to these menu options.

![Screenshot 2022-02-18 at 3 04 57 PM](https://user-images.githubusercontent.com/92800463/154656878-535e9836-834e-42c8-980b-a77cfe9cce35.png)
Aligning these items to the center will be more appealing. 

![Screenshot 2022-02-18 at 3 05 21 PM](https://user-images.githubusercontent.com/92800463/154657069-3e53bfa0-6cf9-4aef-91e1-fc9606e70247.png)
There is space left on the right side, still, products are wrapping on the next line.

![Screenshot 2022-02-18 at 3 05 52 PM](https://user-images.githubusercontent.com/92800463/154657308-fd89fb6f-5e76-4918-ac05-5ad5e2452287.png)
Shadow seems too hard, try to make it subtle.

2022-02-18 13:37 UTC, zoef-yt approved these changes
The code looks good to merge.

2022-02-18 13:37 UTC, zoef-yt commented on components/cart/cart.css
> +    /* box-shadow: 0px 0px 6px 1px var(--navigation-container-shadow); */
remove commented code.

2022-02-18 14:03 UTC, merged